### ISSUE TITLE
Checkin App not working correctly 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#161]
Lake City is reporting check-in system Printing the entire family even though only some of them are checked in for the day. 

For example: say last Sunday, my entire family was at church so we all checked in. Then this Sunday, only Kari, Jon Micheal and Joel are there and I am not. Even though we only checkmark their names, I will still get a label.

**Comment by jzongker** [comment]
By default it pre-populates the classes for everyone, with the classes they attended last time.  I'm guessing it's pre-populating you in this example and the person doing the check-in needs to mark you as none.

Perhaps we should disable that feature?

**Comment by mbyrdLCS** [comment]
I think What he is saying is even though they go in and mark as none it still prints them

**Comment by jzongker** [comment]
Confirmed this is working correctly with 1.25.0
