### ISSUE TITLE
Looping video not working

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#163]
I just found this bug and it really affects every lesson that is out there. Last week we switched everything from.mp4 files to vimeo the .mp4 files had a way for us to mark the videos as looping. That works as expected in the Vimeo files however you mark them as looping and it does not work. A lot of the lessons use this function as a place holder and are auto advancing. We need the vimeo files to loop. 
<img width="511" alt="Screen Shot 2023-06-21 at 8 51 50 AM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/5283e76b-6d72-4b09-ba8f-3816640a3d3d">

**Comment by jzongker** [comment]
Fixed in 2.0.2
