### ISSUE TITLE
Lessons.church scheduling 1 day off

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#190]
https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/2ee6b60b-2cd8-48a1-bcda-00f2bd86b8e1

**Comment by jzongker** [comment]
Just a note - this is almost certainly a timezone thing of GMT vs user's timezone.  Still continue to store the times as GMT, just adjust to local on the client side.

**Comment by Himali-Malvawala** [comment]
Fixed!
