### ISSUE TITLE
B1 Website inside of the B1 app Youtube issue 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#198]
When you use the B1 app to point to the B1 website and there is a video as the section background it pops out and starts playing that video by itself. 

https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/7463abea-8e5e-4ce1-9bce-e487337ceab8

**Comment by jzongker** [comment]
This is fixed now
