### ISSUE TITLE
.mp4 thumbnails are not working 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#199]
This is an odd problem that does not happen to often but here we are 

Engage 1 here https://lessons.church/ark-preschool/the-helper/the-holy-spirit-is-our-guide is a bulk asset of small .mp4 instead of .jpg it is not letting me choose all not sure if there is a way to make it work where it plays all those. mp4s or do we need to figure out another way to put this in?

**Comment by jzongker** [comment]
I'm not sure I fully understand this issue, but it's from last August and the Engage 1 appears to be working correctly on that lesson now, including all the thumbnails.   I'm going to close it, but feel free to reopen (and clarify) if there is still a problem.
