### ISSUE TITLE
Formatting on lessons.church

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#201]
When I use "Do" action type it doesn't keep the formatting. Attached is an example. Can this be changed?
![image_123927839](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/a01aa21a-b049-4ee8-88c9-02b084d4c43e)
![image_1239278391](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/8a014b69-be5b-4452-8254-de49f7eb2598)

**Comment by Himali-Malvawala** [comment]
Done.
