### ISSUE TITLE
App should show church favicon instead of logo

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#202]
App should show church favicon instead of logo

![IMG_9522](https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/d17387f8-a77b-4658-bbac-46daba15f78f)

**Comment by jzongker** [comment]
Default to favIcon when provided.  Fall back to logo when not.

**Comment by jzongker** [comment]
![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/d89419e5-9d7d-4fe3-8377-6b6c445de44a)

It'll now use the square favicon when available.  It looks like Rock Solid doesn't currently have one however.
