### ISSUE TITLE
When adding logo to your account it should snap to that logo

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#203]
When adding logo to your account it should snap to that logo. Currently, the box is above the logo if it is the correct size. 

<img width="1495" alt="Screenshot 2023-09-05 at 11 15 10 AM" src="https://github.com/LiveChurchSolutions/ChurchAppsSupport/assets/65249159/dc8d1a0c-6772-419d-b791-cf3eee5a58a3">

**Comment by Himali-Malvawala** [comment]
Fixed!
