### ISSUE TITLE
Batch dates for giving do not import in on chums from breeze

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#204]
On the import-export app the batch dates do not come in on

**Comment by mbyrdLCS** [comment]
[demo65292b5b5ad2e-giving-10-13-2023.xlsx](https://github.com/ChurchApps/ChurchAppsSupport/files/12893005/demo65292b5b5ad2e-giving-10-13-2023.xlsx)

demo file

**Comment by Himali-Malvawala** [comment]
Fixed!
