### ISSUE TITLE
Lessons.church app

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#212]
Currently, if you use the lessons.church app offline and click the back button the app stops working. If possible we need it to keep working no matter what anyone does.

https://www.dropbox.com/scl/fi/fkcsuar7w2vjkubua8kss/IMG_0290.mp4?rlkey=igoo8wvuxv1u4z1i378uec384&dl=0

**Comment by jzongker** [comment]
Added offline detection for all scenarios
