### ISSUE TITLE
720 vs 1080 with lessons.church

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#213]
720p is great for fast downloads and seems to be working great but as the videos get better in quality it would be nice to have the option to choose 1080p or 720p delivered on the individual videos.

**Comment by jzongker** [comment]
Let's add a setting to the android app for resolution.  Default to 720.  If 1080 is selected, pass ?resolution=1080 in the query string to the two API calls that fetch videos.  (via browse and classroom)

**Comment by jzongker** [comment]
This has been added to the settings tab.
![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/8104c29a-56aa-475f-b4b9-a76921e157a5)

**Comment by mbyrdLCS** [comment]
That is Perfect I like how you worded that

**Comment by mbyrdLCS** [comment]
Is there a way to enable on SP?
