### ISSUE TITLE
Update switchover time for lesson schedules

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/ChurchAppsSupport#216]
Currently if you schedule a lesson for Sunday, it will remain the "current" lesson in the schedule feed until some point on Monday.  This was done to ensure lessons don't switch over too soon for Sunday night services due to timezone issues.

It's causing problems of people want to download the new content on Monday morning and they cannot yet.  We need to either figure out a better way to handle time zones or reduce the buffer to +12 hours instead of +24.

**Comment by vassbo** [comment]
I'm not sure how the backend looks here, I guess it's JSON data, but why not include the data for both the current week and the previous week, and the first date of the current week? 🤔

That way the data can update on the sunday, and can check the time on the local device to determine if we should use the data from the previous week! Use "current" if the data date is today or after, if not use "previous".

**Comment by jzongker** [comment]
You're right.  The device should be determining the current time rather than the api trying to hedge bets.  Rather than changing the data returned by the api, I just had the client pass a ?date= param with the request to tell it which date it should pull for.
