### ISSUE TITLE
Mobile App navigation pane issue

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#217]
In the mobile app the first time you go to a link from the drop down menu on the navigation pane the menu disappears. If you navigate to another link the dropdown menu does not go away until you touch the page. 

![East Bartlesville Christian Church](https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/970e0145-3750-471a-a41b-8cbd6c7d6f37)

**Comment by Himali-Malvawala** [comment]
Fixed!
