### ISSUE TITLE
Forms do not load 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#221]
About 1/2 the time if you have a form on a page it does not load.  You have to go and refresh the page to get it to load a good example is this small form 

https://southsideonline.com/contact

https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/233c34a7-78a3-4cc3-bfac-5ff631e1375b

**Comment by jzongker** [comment]
This issue was fixed back in April.  Closing.
