### ISSUE TITLE
Logo is Stretched in Safari 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#223]
https://southsideonline.com

![IMG_4271](https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/70604209-c8ee-4571-8266-378e8b691e75)

**Comment by jzongker** [comment]
Is this still an issue?  It looks ok to me.

**Comment by mbyrdLCS** [comment]
To me it still looks a little stretched on safari.

Top is Chrome 

<img width="901" alt="Screenshot 2024-01-11 at 6 27 45 AM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/cdff9b10-9582-4ec1-81b1-b21049cdc5ed">

**Comment by mbyrdLCS** [comment]
<img width="1374" alt="Screenshot 2024-08-14 at 12 17 14 PM" src="https://github.com/user-attachments/assets/43ad48bd-7830-4802-bcf2-c0177ae2eef5">

**Comment by vassbo** [comment]
Looks like I'm not the only one with this issue! 😅 I recently had to fix the exact same issue on the FreeShow website, here's my fix: https://github.com/ChurchApps/FreeShowWeb/commit/45842e137178f4f63116b664620ec8c2b8cf9478#diff-ca5e8897da8d7da545ed4146550722b9c36b53c9025d08a2369ac5f2a65d7281

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS The logo should be good now!
