### ISSUE TITLE
Phone field in Forms does not work correctly

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#225]
When entering the phone number if you put the hyphens in, the form will not register the number. If you just type the number with no hyphen it will work but the number looks like this 1234567823 (the hyphens do not auto fill). 
<img width="1185" alt="Screen Shot 2023-10-15 at 5 40 42 PM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/dd258930-aac2-456a-854f-b970d8ee57d2">

**Comment by Himali-Malvawala** [comment]
The issue is fixed. Now the hyphens will automatically get added, we don't have to enter them manually. And In the Chums, it'll be exactly like that (with hyphens).

**https://www.loom.com/share/ab1cf77c9a0b4b5c8678041f5a0c7ac5?sid=a099594d-7ade-4dde-887c-c180ead5402b**

**Comment by Himali-Malvawala** [comment]
Upgraded the phone field to support country select.

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/86650000/f907a7f3-eed1-489b-8fbd-ab031f5d162b)
