### ISSUE TITLE
Carousel B1 Website timed slides 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#226]
It would be nice to be able to set the time for each slide. 

 

<img width="1512" alt="Screenshot 2023-10-17 at 11 30 37 AM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/19ea0a9c-8ab2-47b5-93b3-9360e370b06f">

**Comment by Himali-Malvawala** [comment]
Added!
