### ISSUE TITLE
When no lessons are scheduled 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#227]
Currently when no lessons are scheduled the app just fails to load. This most often results in a call to support saying the app does not work. This is false it is working but you have to load a lesson is it possible to have a message that says you need to schedule a lessons on lessons.church for this to work or something like that?

**Comment by jzongker** [comment]
There are a few duplicates/variants of this issue, but I updated the app to return this message in all scenarios where it can't load the current schedule or it's contents.
![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/53eb4112-e30d-48d5-9bad-c765d3c36744)
