### ISSUE TITLE
Lessons.church app 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#228]
When you make a venue with no slides in it like small group questions or something like that if it is scheduled the app crashes. Should probably just default to an image saying no media for this lesson.

**Comment by jzongker** [comment]
There are a few duplicates/variants of this issue, but I updated the app to return this message in all scenarios where it can't load the current schedule or it's contents.
![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/53eb4112-e30d-48d5-9bad-c765d3c36744)
