### ISSUE TITLE
Giving batches: Sort by date 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#230]
Giving batches: 
We need a way to sort the batches by just clicking the date or name at the top of the batches. This way if I am looking for a specific batch and need details on it, I can find it by batch number or date. Currently, I can’t search either and all the dates and names are out of order. When I imported data in from breeze all the dates were out of order

**Comment by Himali-Malvawala** [comment]
Done!
