### ISSUE TITLE
App Freezes

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#235]
If you go to a church that has nothing scheduled the app freezes the only way to get it back is to clear data.

**Comment by jzongker** [comment]
There are a few duplicates/variants of this issue, but I updated the app to return this message in all scenarios where it can't load the current schedule or it's contents.
![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/53eb4112-e30d-48d5-9bad-c765d3c36744)
