### ISSUE TITLE
B1 Website Builder - Dragging Items in Rows

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/ChurchAppsSupport#237]
There are at least two issues when re-arranging items withing rows.  If they are newly added items, you cannot drag to the top.  I believe this was also an issue on the main page because IDs and indexes weren't set until save.

In addition, there's no way to drag to the bottom of a row column.   We need to add a "Add to bottom of column" area, similar to the "add to bottom of page"

**Comment by Himali-Malvawala** [comment]
https://github.com/ChurchApps/B1App/pull/194
