### ISSUE TITLE
Hard to add Small images anywhere on the website

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#239]
2 issues 

Adding small images 

when you try to add an image under text it does not put it in the correct spot.

https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/f41789c2-a741-4233-a587-506a4e00986f

**Comment by Himali-Malvawala** [comment]
For the image not being in the correct spot, it's a sorting issue. I'm currently working on it. It'll get fixed soon!

**Comment by jzongker** [comment]
By default all images were set to fill 100% of available space.  I've added a "Don't Resize" checkbox to the Image element to override this.  For it to work, you'll need to upload an image that is the size you want.  It will not scale down larger images.
