### ISSUE TITLE
Press Page

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/ChurchAppsSupport#24]
I am wanting a press page where people know they can contact me and talk about LCS and what we do. Or go on and see the direction we are going and be able to download our logos. Encouraging people to share to any church they can.

This is a great example:
https://bibleproject.com/press/

**Comment by mbyrdLCS** [comment]
Using the Same Verb-age: 

 If you are a member of the media, we've put everything you need on this page. Thank you for your interest in Live Church Solutions.

Links to Apps we Offer With the correct logo for each @jzongker do we have a place where all our logos are? 

LCS is based on the concept from Acts 2:44. The early church had “all things in common”. We believe the church should pool its resources by sharing curriculum and technology to free up funds for evangelism.

**Comment by jzongker** [comment]
We have the B1 website builder now where we can create this page.

Will be working on the new ChurchApps website soon
