### ISSUE TITLE
Auto Load Sermons

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#243]
Add an auto load feature to the "sermons" element.  Currently sermons must be manually uploaded each week. 
<img width="1222" alt="Screen Shot 2024-01-12 at 11 03 41 AM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/5e4c0e73-f837-4eeb-a456-a66b41dad07f">

**Comment by Himali-Malvawala** [comment]
To handle this, we now have a checkbox ("Auto Import New Videos") where we bulk import videos. If it's checked, new videos will be added as sermons in the selected playlist. 

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/86650000/2a848104-614e-44de-9ffa-346d0faec50e)


New videos will be automatically imported each night at 12:00 AM.

**Comment by tbyrd77** [comment]
That’s a great feature! Thanks
