### ISSUE TITLE
[CHUMS] Reference to deleted group on person's profile

### ISSUE THREAD

**Issue by kshairrick** [ChurchApps/ChurchAppsSupport#244]
After deleting a group, the reference to the deleted group is still present on an individual's profile.  When a group is deleted, is it possible to unlink the group reference on the person's profile?

In this example, the group "Test2" has been deleted, but it still appears on the profile.

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/50141634/701daa40-0289-4906-a69c-47f819b4fd47)

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/50141634/322a7094-c147-44d2-9bf9-fb18272cdb15)

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/50141634/bff68ae5-a684-49db-9c29-c90475a02754)

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/50141634/1b3bc974-cedb-4e41-96ed-79e9a65f4e68)

**Comment by Himali-Malvawala** [comment]
Thanks for reporting the issue. It'll get fixed ASAP.

**Comment by Himali-Malvawala** [comment]
The issue is fixed!

**Comment by kshairrick** [comment]
@Himali-Malvawala Strange, the front end still seems to show the deleted group (Test2).

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/50141634/97bb2ca1-fd08-4ae5-8fdd-6617642d433a)

**Comment by Himali-Malvawala** [comment]
@kshairrick It should be good now.

**Comment by kshairrick** [comment]
@Himali-Malvawala Yes, it is working now!

**Comment by Himali-Malvawala** [comment]
Great!
