### ISSUE TITLE
CSV Download from Donations

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#245]
Could we add the donor's id and name to the CSV that is downloaded from the Donation Summary? Currently all that is downloaded is the Fund Name, the Total amount given and the date.

**Comment by jzongker** [comment]
The csv portion is complete.  We just need a Word template for the giving report and mail merge instructions.  It would probably be a good idea to create a second mail merge template for envelopes.

**Comment by jzongker** [comment]
@tbyrd77 I believe you were working on the word templates.  Any updates?  I add them to the app when ready.

**Comment by tbyrd77** [comment]
Hi Jeremy,
Here are the templates. I thought I had put them in git hub but evidently not. They are pretty generic but the basic stuff is there so they should be able to go from there. Thanks
 ￼

**Comment by jzongker** [comment]
@tbyrd77 - I'm just now going through old issues.  It looks like you tried to reply to the notification email and attach the template, but GitHub doesn't appear to allow that so they didn't get uploaded.  Could you upload them here?  https://github.com/ChurchApps/ChurchAppsSupport/issues/245

**Comment by tbyrd77** [comment]
[Word Donation Report Template.docx](https://github.com/user-attachments/files/17531457/Word.Donation.Report.Template.docx)
It won't accept the pages document.

**Comment by tbyrd77** [comment]
Hi Jeremy,
Git hub won’t accept the Pages document. Here it is. I uploaded the Word doc to Git hub. 
￼

Thanks

**Comment by jzongker** [comment]
This is live now.  I think the Word document is the better route anyways.
