### ISSUE TITLE
Subtract deleted donations from Giving Summary

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#247]
When a donation is deleted from a batch is there a way to automatically subtract it from the Donation Summary? The only way to remove it now is to make a negative donation.

**Comment by Himali-Malvawala** [comment]
Strange. I deleted a donation from a batch, and it got removed from the donation summary too. Can you try deleting one again?

**Comment by tbyrd77** [comment]
Yes, it seems to be working now. I don’t know what the problem was but it’s fixed now. Thanks

**Comment by Himali-Malvawala** [comment]
Great!
