### ISSUE TITLE
International numbers in Chums

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#249]
Add international format to phone numbers in Chums database. 

e-mail from user:
Good evening, I am writing to you from Italy.
 
I found Chums, it seems very interesting and I would like to use it to improve the management of our small church.
 
I'm having some trouble entering phone numbers because it seems like they are automatically formatted as US numbers.
For example, if I enter the number "+39 340 1234567" which is a classic Italian format, this is transformed into "+3-934-012-34567".
Is it possible to set the international settings?
 
Thank you for your work and blessings from Italy
 
Gianfranco Bruno

**Comment by Himali-Malvawala** [comment]
@tbyrd77 International settings have been added to the phone numbers.
