### ISSUE TITLE
Add delete option to attendance

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#259]
You can delete groups but their attendance still shows up on the graph. I would like to be able to delete all attendance (or certain dates or groups) and start over. In the screen shot you can see that the groups have been deleted but the attendance chart remains. 
<img width="1265" alt="Screen Shot 2024-03-25 at 9 11 29 AM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/4c787247-5877-4c1c-a3bd-9067f974016c">

**Comment by jzongker** [comment]
Let's update the report to filter these out rather than actually removing the data.  I could see other scenarios where a class is discontinued but the church doesn't want their historic attendance records modified.
