### ISSUE TITLE
Add a mass delete option to People

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#260]
Currently you can only delete people one file at a time. It would be nice to have a way to delete several files at once and have a "delete all" option.  This would need to come with a "This action can not be undone" warning or possibly archive these files then they can be deleted from the archive if the user was sure they would not want to access them.

**Comment by jzongker** [comment]
What do you think about adding an option on the filter for "Delete Option".  If they select it, little trash can icons will appear next to people in the list so you can just go down it clicking the icon next to those you want to get rid of?

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/f5882182-d2aa-4411-aff9-3158e9b7b819)

**Comment by tbyrd77** [comment]
That’s great! ThanksSent from my iPhoneOn Apr 6, 2024, at 12:08 PM, Jeremy Zongker ***@***.***> wrote:﻿
What do you think about adding an option on the filter for "Delete Option".  If they select it, little trash can icons will appear next to people in the list so you can just go down it clicking the icon next to those you want to get rid of?
image.png (view on web)
