### ISSUE TITLE
Timing Issue when opening pages that have forms on them

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#262]
When I try to open this page https://frciola.com/prayerrequests 1/2 the time I get this error.

<img width="1180" alt="Screenshot 2024-04-05 at 8 18 17 PM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/1bec2793-b2eb-4a0c-8d14-694a9766c2d3">

**Comment by jzongker** [comment]
?churchId=undefined is the reason for the error.  Need to figure out why it's undefined.  I assume there are multiple API calls and the order in which they complete varies.

**Comment by jzongker** [comment]
This is a duplicate of issue #221
