### ISSUE TITLE
Lessons.Church will not let you add bullets program is crashing

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#266]
When I click on Normal the Page goes White Every time. 

https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/2e19b417-99ed-4763-87ba-76d920d1bbb4

**Comment by Himali-Malvawala** [comment]
I've figured out what's the problem. I'll fix it as soon as possible!

**Comment by Himali-Malvawala** [comment]
Fixed!
