### ISSUE TITLE
Snaping to 16:9 full image In Lessons.church

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#267]
Orignally we had a lot of old material that was 4:3 so we made this snap smaller but now where ever you upload an image for covert art in lessons.church there are a couple it should auto snap to the whole window so we do not have to drag it to the sides every time. 
<img width="1435" alt="Screenshot 2024-04-14 at 4 49 03 PM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/29e5ef09-757d-41c0-b7ff-0acd26f1ce62">

**Comment by Himali-Malvawala** [comment]
This is fixed now. It'll auto-snap to the full image if it's 16:9.
