### ISSUE TITLE
User defined search and download

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#269]
Currently no user defined information is available in the people download. For example: if I create a form which adds this information to the data base " Baptized, Yes/No" or "Baptism Date" I would like to be able to search that information or at least have it included in the CSV.  Using this example I could identify everyone in the congregation who is baptized or identify everyone who was baptized after a certain date.

**Comment by jzongker** [comment]
Let's rework the UI on this popup to make the list more condensed, or maybe use a dropdown of available fields with an Add button.  The fields from Forms tied to people will need to appear as optional fields to include.

![image](https://github.com/ChurchApps/ChurchAppsSupport/assets/1447203/947f61a9-d5d4-487d-aa91-9a30840f3cb8)
