### ISSUE TITLE
Problems with Conversations and messages

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#272]
I'm using a MacBook Pro M1. The Conversations tab is not showing up. Also, sometimes when I click on the notification bell I get a blank white screen and the program locks up.

**Comment by jzongker** [comment]
@tbyrd77 Could you confirm if this is still broken?  I tried on my M1 Macbook Air and it seems ok now.  I think we can close this.

**Comment by jzongker** [comment]
The chat is working on all platforms now
