### ISSUE TITLE
Checkin App Search

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#285]
The search function of the checkin app says to enter your phone number.  If you enter your full phone number it doesn't work. It would be better if it said "Enter last four digits of your phone number" or something to that effect. 
![91960F12-4BC2-44D3-9313-B308103682FC_1_102_o](https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/c3eca6be-2146-49c2-87dc-14b8c833df63)

**Comment by jzongker** [comment]
Deployed 1.25.2 with this fix.
