### ISSUE TITLE
B1 Issue Text disspaerring

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#287]
https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/ae49a922-29f8-4b64-84ca-4d9c1160bad7

**Comment by Himali-Malvawala** [comment]
I guess the heading color for the section is white. Can you change to a different color?

https://github.com/ChurchApps/ChurchAppsSupport/assets/86650000/25b28e15-5f1f-4ce2-95fd-18450aacf60a

**Comment by mbyrdLCS** [comment]
Thank you yes that is the issue.
