### ISSUE TITLE
MembershipApi initdb error - Missing files in ApiHelper

### ISSUE THREAD

**Issue by vassbo** [ChurchApps/ChurchAppsSupport#298]
Tried setting up the MembershipApi, but running `npm run initdb` caused an error due to missing `settings.mysql`.
The MembershipApi error is from the DBCreator in the ApiHelper file: https://github.com/ChurchApps/ApiHelper/blob/main/src/helpers/DBCreator.ts

Figured out this is based on the deprecated ApiBase: https://github.com/ChurchApps/DEPRECATED_ApiBase/tree/7ee5a60cb2a6f93e35df4213fcaa700af2e348eb/tools/dbScripts

The fix (I guess): Either add the three missing files directly into the MembershipApi and update the `initdb.ts` file, or add them into the new ApiHelper and update the `DBCreator.ts` file.

**Comment by jzongker** [comment]
Fixed with https://github.com/ChurchApps/MembershipApi/commit/1e833b4c96fd8eb6cf3bfa1eafb8887986d5d05e

You're right, initDB is the one file outside of the main project without typescript validation and hadn't been updated when appBase was deprecated.
