### ISSUE TITLE
Payment option in Forms

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#300]
Can we put an option for payment (donation) within forms? If we linked the form to the donation page a person could register and pay for an event using forms.

**Comment by jzongker** [comment]
This is no longer a "donation" right?  As far as tax deductions are concerned.  It's a purchase.  So we'll need a way to mark some transactions as not tax deductible?

**Comment by tbyrd77** [comment]
Hummm, I didn’t think of that. That is correct. The question came from a church camp that is using the online registration form and they would like for people to pay their fees at the same time.

**Comment by jzongker** [comment]
Ok.  I added issue #303 as a prerequisite to this to track non-donations separately.

**Comment by Himali-Malvawala** [comment]
Added!
