### ISSUE TITLE
B1 app exsiting user trying to make an account should have an error message 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#301]
When an existing user tries to create a new account on the app, it gets stuck (at least on the iPhone). Please refer to the attached image for reference. I believe it should display an error message stating, "This user already exists. Please log in with your username and password."

![b1 app error](https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/b6433995-3401-4edc-bd74-c5741f5d4340)

**Comment by jzongker** [comment]
This is fixed with https://github.com/ChurchApps/B1Mobile/pull/77 but I'm going to wait until it's deployed before closing
