### ISSUE TITLE
Email introuding a teacher to the B1 church app.

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#302]
Possible welcome email to teachers when added to a classroom. 

Welcome Thank you for serving in the ___ classroom 
Download B1.church
Login using this email address.

<img width="1507" alt="adding member to classroom" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/65249159/856c4a23-c13b-4e7e-8c18-c62193d13645">

**Comment by jzongker** [comment]
I don't think we can reasonably do this on an automated basis.  All the system knows is they are added to a volunteer team of some type.  Could be teaching, singing, running video, security, etc.  Each are going to have different needs and need different emails.

I think the best we could do is have some templates where churches can store draft emails.  Then let people choose from a template when they use the new message group option #280 or private messaging an individual.
