### ISSUE TITLE
Plans crashes on occasion 

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#305]
When working with Plans trying to edit something in a plan it will randomly crash.  Usually with a blank screen but occasionally with this message. 
<img width="1196" alt="Screenshot 2024-06-20 at 11 51 27 AM" src="https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/7995246d-8837-47c1-8184-2843403875ec">

**Comment by jzongker** [comment]
I'll keep an eye out for it.  If it happens again, can you press control-shift-i to launch the Chrome inspector and take a screenshot of the console tab?

**Comment by tbyrd77** [comment]
Will doSent from my iPhoneOn Jun 20, 2024, at 5:24 PM, Jeremy Zongker ***@***.***> wrote:﻿
I'll keep an eye out for it.  If it happens again, can you press control-shift-i to launch the Chrome inspector and take a screenshot of the console tab?

**Comment by tbyrd77** [comment]
Here is a screen shot but I’m not sure it tells you everything you need to know. Is there a way for me to download the entire thing and send it to you?￼

**Comment by tbyrd77** [comment]
This might be better.
￼

**Comment by Himali-Malvawala** [comment]
@tbyrd77 Can you upload a new picture? I'm unable to see the above ones.

**Comment by tbyrd77** [comment]
Here is a jpeg
![Screenshot 2024-06-21 at 9 34 49 AM](https://github.com/ChurchApps/ChurchAppsSupport/assets/127863068/70490efa-4337-43dd-91eb-463f1f47b464)

**Comment by tbyrd77** [comment]
This is the first one I sent
![Uploading Screenshot 2024-06-21 at 9.30.44 AM.jpg…]()

**Comment by Himali-Malvawala** [comment]
Thanks!

Since the label was for chums, I thought it was a chums problem but it's actually in B1. It's fixed now. I'm sure it'll be up in the next production build.

**Comment by tbyrd77** [comment]
Sorry I labeled it wrong. Thanks for fixing it. Sent from my iPhoneOn Jun 30, 2024, at 12:09 PM, Himali Malvawala ***@***.***> wrote:﻿
Thanks!
Since the label was for chums, I thought it was a chums problem but it's actually in B1. It's fixed now. I'm sure it'll be up in the next production build.
