### ISSUE TITLE
Time change in Plans does not work

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#306]
If you try to change the time of an event it will go back to the time it started as. In the following video you can see where I tried to change the time to 7:30 and after I did it reverted back to 2:30
[Plans.mov.zip](https://github.com/user-attachments/files/15920102/Plans.mov.zip)

**Comment by jzongker** [comment]
It was saving ok, but all times were off by 5 hours in central time zone due to it making unnecessary time zone adjustments.  It's fixed now.
