### ISSUE TITLE
Deleting Volunteer Groups in Plans

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#339]
When you delete a volunteer group in Plans it stays on the menu.  If you create a group with the same name you can't distinguish which is which when you choose a group for your plan. It would be good if when the group is deleted it would be removed from the menu.  

https://github.com/user-attachments/assets/0a316c9c-3cc5-4500-953c-95f4d8fc0733

In the video there are 4 volunteer groups called "Ushers".  Each group is made up of different people.  It is impossible to tell which is the current group. Three groups have been deleted but remain on the menu.

**Comment by Himali-Malvawala** [comment]
The problem is when we delete a ministry, the teams inside it are not removed, hence the long list of teams in the volunteer groups field. We can prevent that by removing the teams when we delete a ministry.

We can add a spell/name check for teams with identical names.
