### ISSUE TITLE
 Feature Request for B1 Website Builder

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#340]
https://www.rightnowmedia.org/us/mission

https://github.com/user-attachments/assets/b80280f7-465e-4f6b-bcbc-02758bf65714

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS That does look cool! 
I guess we can call it the Hero section or something like that. What do you think @jzongker?

**Comment by jzongker** [comment]
Expanding this to be more generic transitions - #407
