### ISSUE TITLE
Tasks notifications isn’t alerting

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#343]
When you make a task I thought it was suppose to make a notification to the person who needs to do that task this is not working it would be nice if this would also send an email to that person.

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS   Yep, you are right it doesn't send a notification. I'll make sure to add that.

Also, we don't need to send those emails individually. It'll send notifications via push or email, right @jzongker?

**Comment by jzongker** [comment]
@Himali-Malvawala It should use the existing notification system, not anything new.

1. If in a web app the bell icon shows up there via sockets
2. If not but mobile app is installed, push notification is sent.
3. If neither email notification is sent.

This is already the behavior MessagingApi uses

**Comment by Himali-Malvawala** [comment]
Ah, Gotcha!

**Comment by Himali-Malvawala** [comment]
@jzongker What if the task is assigned to a group? Send the notification to the group members?
