### ISSUE TITLE
Android App Donation Tab currently Not working correctly

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#345]
Someone with an Android phone please check and see if this is the same or if this was a weird phone that I was working with.

On android app donation, adding a card is very unclear. 

You can’t see what fields you are filling in. 

It doesn’t give an option to cover the fees. 

When typing it doesn’t show up in the box as you type. 

Every time you hit save, it charges your card.

**Comment by jzongker** [comment]
These are fixed in 1.10.6 which was just published.
