### ISSUE TITLE
Lessons.Church Showing the wrong lesson name / Title 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#346]
It is showing the Lesson it should be showing the Title.

![Screenshot 2024-07-31 at 3 47 55 PM](https://github.com/user-attachments/assets/8671915c-a016-47fe-8c0d-721f6c2c2046)
<img width="1512" alt="Screenshot 2024-07-31 at 3 51 46 PM" src="https://github.com/user-attachments/assets/8a376d6c-c1d5-46b8-a2a4-e21987398696">

**Comment by jzongker** [comment]
Fixed with https://github.com/ChurchApps/LessonsApi/commit/6fdc63bfd9058c3bce03fff4f19acb608ccded3f
