### ISSUE TITLE
Subscribed Teacher Lesson Links not working

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#348]
https://lessons.church/classroom/5a-CriJQpig?upcoming=1

If you click on either link here it has this 

<img width="1512" alt="Screenshot 2024-08-01 at 8 57 19 AM" src="https://github.com/user-attachments/assets/4a07aa6b-04cc-44a7-8297-7809ca58574a">

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS  Is this still an issue? 

I opened the link and it showed me the upcoming lesson
![image](https://github.com/user-attachments/assets/0467e941-f022-48dc-8313-da4fc72f17c5)

**Comment by Himali-Malvawala** [comment]
There was an issue with the study slug. It's Fixed!
