### ISSUE TITLE
Printing function for customized material is not working

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#350]
https://github.com/user-attachments/assets/7e6a252f-63fb-4098-ba3e-06b78da0a608

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS we now have a print button on B1!

![image](https://github.com/user-attachments/assets/7fa4e231-9082-470b-bbe4-d101ee7102f5)

**Comment by mbyrdLCS** [comment]
This is working great on the web App I see it is also in the B1 app but when you print using ios nothing happens

**Comment by jzongker** [comment]
I'll have to handle that part within the app itself @Himali-Malvawala .  @mbyrdLCS Can you print from Chrome/Safari on iOS, just not the B1 app?

**Comment by mbyrdLCS** [comment]
Correct just can not print in the app.

**Comment by jzongker** [comment]
This is "fixed" now.

The inability to print from react-native-webview is a known issue with no current solution.  https://github.com/react-native-webview/react-native-webview/issues/1309

As a work around, the print button now open the same page in a browser and triggers the print action automatically.  Hopefully we can clean this up if/when that issue gets resolved.

**Comment by jzongker** [comment]
The B1Mobile version with the fix is 1.10.2

**Comment by Med-Amine-Fredj** [comment]
+1 , any updates ?
