### ISSUE TITLE
Plans Broken

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#351]
https://github.com/user-attachments/assets/1e64e538-5253-46cb-a8ff-f8330d385680

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS Can you share a picture of the console?

**Comment by tbyrd77** [comment]
This is the same as issue #305. Is there a way to make the program produce an error such as " You do not have any assignment teams" and redirect to set up a team instead of going to white screen?

**Comment by Himali-Malvawala** [comment]
It has teams, but I guess Micheal created Times before creating a team, hence the error.

![image](https://github.com/user-attachments/assets/fa3d9374-0ff4-4cb8-839f-5d64c642b526)

**Comment by mbyrdLCS** [comment]
Thank you But I want to leave this open we need to somehow fix this so that it can not happen again it is natural to create times before teams. So we need to make the program where it does not allow this or we are going to have people making this error all the time.

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS  I've fixed it, so it'll show an error if no teams are selected or they create time first. Plus I've attached a [link to this article](https://support.churchapps.org/chums/plans.html) making it easy for them to set up. It'll be up in the next production build.

Also @tbyrd77, can you [update this](https://support.churchapps.org/chums/plans.html)? There are no steps for how to set up time. It directly shows the last step (i.e. notify volunteers).

**Comment by mbyrdLCS** [comment]
Perfect thank you @Himali-Malvawala

**Comment by tbyrd77** [comment]
Yes I’ll get that updated. ThanksSent from my iPhoneOn Aug 10, 2024, at 10:32 AM, mbyrdLCS ***@***.***> wrote:﻿
Perfect thank you @Himali-Malvawala
