### ISSUE TITLE
Text Element Issues

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#355]
The auto size and the link feature of the text element are not working. 

https://github.com/user-attachments/assets/72f0ac01-caaa-4558-8871-bccf63a6f982

**Comment by Himali-Malvawala** [comment]
Can you try it again? I just tried and it's working for me.

https://github.com/user-attachments/assets/15225ff3-923b-49e8-8925-b0aeb123c50e

**Comment by tbyrd77** [comment]
It seems to work on other web pages but not when I am trying to edit the ChurchApps page. I'll keep messing with it and see if I can figure it out.

**Comment by tbyrd77** [comment]
I figured out the problem. The dialog box shows up out of my screen. When I zoom my screen out I can see it. Is there a way to make sure the dialog box opens on top of the link?

https://github.com/user-attachments/assets/1aa2c922-4fec-45b4-b14d-aefb754623d9

**Comment by Himali-Malvawala** [comment]
Fixed!
