### ISSUE TITLE
Error on contact form 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#357]
Every time you go to this page https://frciola.com/prayerrequests you get this error (Server error when loading https://membershipapi.churchapps.org/forms/standalone/0NfiQOpp40W?churchId=undefined) and it will not load to make it load you have to refresh 

Same Here
https://southsideonline.com/contact
Server error when loading https://membershipapi.churchapps.org/forms/standalone/lk-i3opV8JH?churchId=undefined

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS @jzongker I think I know why the church ID is undefined.

https://livechurchsolutions.slack.com/archives/C074JQBDZ9B/p1719580718856489

**Comment by jzongker** [comment]
Sorry I missed your note on Slack, @Himali-Malvawala !

The best I can tell this is working ok now.  I loaded each of those pages about a dozen times without issue.  Can you or @mbyrdLCS give it a try and let me know if the error still exists?

Almost all of the churches are using a custom domain name.  There's a server called Caddy that translates southsideonline.com to southside.b1.church.  In theory, the app shouldn't be aware that a custom domain is used.

**Comment by Himali-Malvawala** [comment]
@jzongker It works perfectly when we directly load /contact the page. The issue is when we switch from a different page to /contact. I hope this video clears out the problem.


https://github.com/user-attachments/assets/baed5752-8bd8-455b-9e8b-d7220c41d4a6

**Comment by Himali-Malvawala** [comment]
@jzongker Fixed this! The error no longer exists and the form works perfectly.
