### ISSUE TITLE
Automated Tasks are not showing up

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#361]
Automated tasks don't show up when you click "tasks". The first screenshot shows that the regular task is showing up but no automated tasks. The second screen shot shows what automated tasks have been created. 
<img width="1414" alt="Screenshot 2024-08-29 at 11 45 26 AM" src="https://github.com/user-attachments/assets/404276df-81c3-4de4-952f-4120b8427f70">
<img width="1416" alt="Screenshot 2024-08-29 at 11 46 11 AM" src="https://github.com/user-attachments/assets/123a092c-e7d2-4a9a-8889-fc3f38fcef36">

**Comment by tbyrd77** [comment]
Yes, I think that is how it is supposed to work.

**Comment by Himali-Malvawala** [comment]
Okay. How about we display the assigned automated tasks here instead?
![image](https://github.com/user-attachments/assets/615d538e-1c27-4b7a-9565-e340c686a071)

**Comment by tbyrd77** [comment]
That would be ok, Is the person who is assigned the task supposed to get notified? Also, how will the person know when a task is due? In other words, if a person is assigned to send cards to all visitors, how will they know who to send the cards to? Or if they are to send cards to all birthdays in August, where will the list of August birthdays be?

**Comment by Himali-Malvawala** [comment]
To be honest I believe @jzongker can probably answer better than me regarding the desired result.

**Comment by jzongker** [comment]
The automations are rules for creating new tasks, but aren't tasks themselves.

You would create an automation to take a visitor to lunch, assign it to John Doe, and set a condition of membershipStatus='visitor'. 

Whenever a new person is added with a membership status of visitor, that automation will create a task and assign it to John Doe.  It will show up in the task list for John, so he never fails to invite a new visitor to lunch.

**Comment by jzongker** [comment]
I don't believe there's anything to be done here.  I'm going to close this out.

**Comment by tbyrd77** [comment]
Ok, I must be setting it up incorrectly because the automated tasks were not being created. I’ll work with it some more and keep you updated. Thanks
