### ISSUE TITLE
Auto size is not working all the time

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#362]
This is the same issue as #355 which has been closed. The auto size box only opens occasionally so the only way to change the size is with the style editor.

https://github.com/user-attachments/assets/e6108ed6-7180-40b8-b41f-13fd3ffaad69

**Comment by Himali-Malvawala** [comment]
It has been fixed but not pushed to production. I'm sure it'll be up this Monday!

**Comment by tbyrd77** [comment]
Sorry I thought it went out last Monday. Thanks
