### ISSUE TITLE
Donations Button not working on B1

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#363]
When setting up donations, a button appears on the app regardless of whether you're logged in or not. However, the button only works when you're logged in. If you're not logged in, it seems like there's no link attached to the button, rendering it non-functional.

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS Can you share an image or a video?

**Comment by mbyrdLCS** [comment]
Sure also this is ios


https://github.com/user-attachments/assets/070e5a7d-f871-4a43-92ac-600900f4c013

**Comment by jzongker** [comment]
Fixed.  Will deploy after the conference
