### ISSUE TITLE
VOTD

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#364]
On Our website https://votd.org/  The view all has stopped working.

<img width="1495" alt="Screenshot 2024-08-31 at 6 42 17 PM" src="https://github.com/user-attachments/assets/e75f8db8-e271-4a64-8d4f-fe6116283a47">

**Comment by jzongker** [comment]
I believe the json url just needs to be updated from livechurchsolutions.github.io to churchapps.github.io

**Comment by KZongker** [comment]
Believe I've fixed it here: https://github.com/KZongker/VotdContent/commit/a8298d17777937dfcf89106549b79c24e4aac572
