### ISSUE TITLE
Changing Category Names 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#365]
I do not see a way to change the name or to delete a category if this could be added that would be great.

  
<img width="1511" alt="Screenshot 2024-09-01 at 3 47 11 PM" src="https://github.com/user-attachments/assets/3b699b0f-a24c-4c5a-97a5-754f9ebd6f39">
<img width="1511" alt="Screenshot 2024-09-01 at 3 48 09 PM" src="https://github.com/user-attachments/assets/f3961c93-b488-4be6-b39a-b5d4895e9b7d">

**Comment by jzongker** [comment]
There's not really a category record to modify here.  To delete a category, you just remove all studies from it.  To rename one, you create a new category and add the studies to it, then delete them from the old one.
