### ISSUE TITLE
Lessons.Church Front page login video thumbnail

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#367]
I know it took a bit of doing for this video to show correctly and it works but would be nice to have the thumbnail on the video right now it just shows a broken image. 

<img width="1512" alt="Screenshot 2024-09-04 at 9 31 12 PM" src="https://github.com/user-attachments/assets/46cf3d86-3e42-4d73-9370-556f5b269b3b">

video file is here https://vimeo.com/manage/videos/985348183

**Comment by jzongker** [comment]
I changed the visibility from "Hide from Vimeo" to "Unlisted" to resolve.
