### ISSUE TITLE
iphone specific link issue  

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#368]
On the iPhone. We have a link to SignUpGenius on our app. The iPhone goes to a short second blank video and the android does not. 

https://m.signupgenius.com/#!/showSignUp/10C0E4BAAAA22A5FE3-51054411-soup/33535683

https://github.com/user-attachments/assets/8180bf94-cb36-47e7-b45d-c67d50900682

**Comment by jzongker** [comment]
Fixed in 1.10.7
