### ISSUE TITLE
Text element dialog box problems

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#369]
In the text element of the website builder when you select a text to make a link or a button the second dialog box opens behind the first box so you can't access it to make a button etc. 
<img width="1265" alt="Screenshot 2024-09-12 at 2 05 21 PM" src="https://github.com/user-attachments/assets/5a9772d8-38ea-4be1-bcfd-e765089eeb12">

**Comment by Himali-Malvawala** [comment]
FIxed!
