### ISSUE TITLE
Add controls to sermon videos 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#370]
Right now when you use our sermons section there is no way to fast forward or rewind these videos we need to make it so that works

https://southsideonline.com/sermons

**Comment by jzongker** [comment]
To test locally, set .env to production and navigate to http://localhost:3301/southsideonline/semons.

**Comment by jzongker** [comment]
Fixed with https://github.com/ChurchApps/B1App/commit/3e1cf6c22dd0d67cbbc718bdddc47213d6f1aab8
