### ISSUE TITLE
Can't reposition pages

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#378]
Some of the pages in the main navigation and not linked pane will not move. The top ones work ok but when you go down they will not move. 

https://github.com/user-attachments/assets/50c8280d-3fc9-4e50-b9cc-1fbac2cc526d

**Comment by Himali-Malvawala** [comment]
@tbyrd77 When you try to move the links, can you keep the console tab open on the side? I guess there might be an error.

**Comment by jzongker** [comment]
@tbyrd77 - I'm unable to reproduce this on the same account.  Can you try closing and re-opening your browser to see if that fixes it?  If not, please let me know which browser and OS you're using and I'll try with the same combo.

https://github.com/user-attachments/assets/7f2b8b4a-64f1-4800-812c-5f9bdbf0fc46

**Comment by tbyrd77** [comment]
It is working now. I’m not sure what the problem was. You can close the issue. Thanks
