### ISSUE TITLE
Menu bar on new page not working

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#379]
https://freecurriculumstinks.com/   is the site I am working on I added a new page called worship now it will not let me click on the menu bar on that page only.

https://github.com/user-attachments/assets/1d69b633-9670-4938-ad9a-e8683d264c80

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS I looked into the section for /worship and I saw 2 elements in that. The first one is correct and the second is just the title and half styling (with an open <style> tag). Can you remove the second element?

1st element:
<body>

    <h1>Free To Use Worship Resources</h1>

    <div class="curriculum">
        <h2><a href="https://kidkardia.com/">Kid Kardia</a></h2>
        <p>Kid Kardia inspires kids and adults to have the heart of a child, just as Jesus encouraged in Luke 18:16. Through their resources, they aim to nurture a childlike faith in both kids and grown-ups, helping them connect with God in a meaningful, engaging way. Visit their website to explore free materials designed to cultivate spiritual growth and discovery for all ages.</p>
    </div>

    <div class="curriculum">
        <h2><a href="https://www.bigbigworship.com/">Big Big Worship</a></h2>
        <p>Big Big Worship is a FREE worship resource for Kids Pastors and leaders. It contains everything you’ll need to create an incredible Worship experience for your kids. From lyric and motion videos to chord charts, Bible stories, memory verses, and more, everything is ready for download. All resources are free and yours to keep. Browse their site to explore worship content designed to inspire and engage your kids in a meaningful worship experience.</p>
    </div>

</body>

**Comment by mbyrdLCS** [comment]
Yes thank you sorry I did not see that!! working great now.
