### ISSUE TITLE
Chums Chek-in app number behavior 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#380]
The video is not great but you can see the issue I belive it is because of the +1 it seems some records it is forced and those records you can not search with a whole phone number but other records do not have to have the +1 and they work. 

https://github.com/user-attachments/assets/122e0e98-14fc-4f73-a322-eb2a392c21ce
<img width="1501" alt="Screenshot 2024-09-20 at 1 00 18 PM" src="https://github.com/user-attachments/assets/8c37fa8e-83f7-4a3d-bb95-3e4116b6bb2c">
<img width="1501" alt="Screenshot 2024-09-20 at 12 59 57 PM" src="https://github.com/user-attachments/assets/c3e3af4f-d436-4363-ac0c-c68d95d92a29">

The correct behavior in the app should be if it sees all those numbers together to pull up that family.

**Comment by jzongker** [comment]
MembershipApi/person/search/phone needs to be update to ignore spaces in addition to "-"

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS @jzongker This is fixed!
