### ISSUE TITLE
Lessons.Church written scripts  is not working for Teachers to teach the lessons 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#381]
https://github.com/user-attachments/assets/2e6cdfcb-2402-4ea7-a0cf-afc1fd98338c

**Comment by jzongker** [comment]
I believe this is fixed.  Let me know if not.  
![image](https://github.com/user-attachments/assets/c3e1fe2c-aec8-4835-a725-db2a9e28a189)
