### ISSUE TITLE
yes/no toggle to show login link

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#383]
Needing a yes/no toggle to show login link some sites like this one just don't need a login.

<img width="1512" alt="Screenshot 2024-10-01 at 10 24 39 AM" src="https://github.com/user-attachments/assets/aac9e472-5bd2-47c2-9a3b-1a507fdc00c7">

**Comment by Himali-Malvawala** [comment]
Added! 

It'll be up in the next production build.
