### ISSUE TITLE
Group search

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#385]
Can we add the advanced search feature to the group "Add Person" box? The only option we have now is to search for an individual or search the entire data base. This would allow us to set up groups with certain criteria. For instance: If we wanted to create a group which includes all the men who are members of the church who are 18 and older. It would also be good to have an add box at the top where we could add all the people on the list without going through the whole list checking each box.  
<img width="1130" alt="Screenshot 2024-10-02 at 10 25 33 AM" src="https://github.com/user-attachments/assets/868d81f0-5c93-4891-90b9-5f890aabfb0a">

**Comment by jzongker** [comment]
This is live now
