### ISSUE TITLE
Style "Border" does not work 

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#386]
When you add a border to an image, nothing happens. 
<img width="807" alt="Border 1" src="https://github.com/user-attachments/assets/53b2421b-7d87-4535-9063-d01f3a736f83">
<img width="393" alt="border 2" src="https://github.com/user-attachments/assets/5308a13b-7669-4e58-8542-e99cdc034d31">

**Comment by Himali-Malvawala** [comment]
It's Fixed!
