### ISSUE TITLE
Links problems

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#391]
The links on our websites are working but are showing codes. 
<img width="1273" alt="Screenshot 2024-10-14 at 2 18 56 PM" src="https://github.com/user-attachments/assets/49218f4d-69a7-44ea-955e-2775e5507395">
<img width="1263" alt="Screenshot 2024-10-14 at 2 20 51 PM" src="https://github.com/user-attachments/assets/8f8aa5bb-d904-4c72-9f36-195447ffcc3c">

**Comment by jzongker** [comment]
Updated the MarkdownPreviewLight to support css classes on links.
