### ISSUE TITLE
Empty GO home page

### ISSUE THREAD

**Issue by vassbo** [ChurchApps/ChurchAppsSupport#394]
![image](https://github.com/user-attachments/assets/9696ade5-0a4c-49a8-a5c4-fc710ac77297)

Clicking the ChurchApps logo in the top left of a GO page as linked below, takes you to an empty home page:
https://go.churchapps.org/freeshow-insiders-group

![image](https://github.com/user-attachments/assets/a416a1f6-8f39-4990-a6b9-c5eb63ab1af2)

We should redirect to https://churchapps.org instead if this page is not in use.

**Comment by mbyrdLCS** [comment]
This was a hub-spot error they have fixed it.
