### ISSUE TITLE
Attendance page dowload produces a donation report csv

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#397]
The attendance page creates a report for donations. Also, the top "Detailed Summary" has a donation icon. It should be the attendance icon. 
<img width="1251" alt="Screenshot 2024-10-23 at 7 09 24 AM" src="https://github.com/user-attachments/assets/794a8fea-b862-4451-a23b-7a6e7cccb81d">
<img width="1343" alt="Screenshot 2024-10-23 at 7 08 47 AM" src="https://github.com/user-attachments/assets/65c4582d-80d9-4c9b-b150-8d203f0d3dba">
<img width="1348" alt="Screenshot 2024-10-23 at 7 07 37 AM" src="https://github.com/user-attachments/assets/93de203e-2735-44ee-b68c-c9c02fa4d9d4">

**Comment by Himali-Malvawala** [comment]
Fixed!
