### ISSUE TITLE
Adding Category for Add ons in lessons.church 

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#398]
Can we add a category called Christmas Songs?

 
<img width="1488" alt="Screenshot 2024-10-24 at 6 41 51 AM" src="https://github.com/user-attachments/assets/3a92c427-e769-4fd0-8f61-b20b19733763">

**Comment by jzongker** [comment]
Yeah, I just named it "Christmas" in case there are Christmas games or other content in the future.  Went ahead and added Easter as well.
