### ISSUE TITLE
B1 Group Calendars Not Handling Time Zones

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/ChurchAppsSupport#412]
If you schedule an event for noon central time, and go back to view it, it'll show 6am central time instead.  We need to make sure the times reflect the current time zone correctly.

Adjust the time to GMT before saving to the database, and adjust it back to local time when displaying.

**Comment by jzongker** [comment]
It looks like the recurring schedule is also off.  If you have an event on Tuesday and set it to recur weekly, it shows wednesday.

**Comment by Himali-Malvawala** [comment]
The off-schedule part for recurring events is fixed! [#413 ](https://github.com/ChurchApps/ChurchAppsSupport/issues/413)

**Comment by Himali-Malvawala** [comment]
Finally, this is now fixed!
