### ISSUE TITLE
Some recurring rules don't work on group calendars

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/ChurchAppsSupport#413]
Scheduling a recurring event for the 3rd Saturday of each month for example will throw an error when you try to view the calendar.  I believe there are two different RRULE standards here and there's a mismatch between the rrule library we're using and the calendar component that generates the rrules.

https://github.com/jkbrzt/rrule/issues/361#issuecomment-736306406

**Comment by Himali-Malvawala** [comment]
@jzongker This is fixed!

We just needed to switch from `bynweekday` to `byweekday` and `bysetpos`.
