### ISSUE TITLE
Clean up forms

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#417]
Can we make the forms have a more consistent look? Some of the fields have the words in the top line and others have them in the box. Could we space the fields out and make them look more like the second example?
![Booking - New Life Restoration Ministries](https://github.com/user-attachments/assets/43b02b21-7ce4-40b9-b97f-ae20dc372963)
<img width="816" alt="Example 2" src="https://github.com/user-attachments/assets/09e2d239-309e-4732-8f48-e95846128fba">

**Comment by jzongker** [comment]
The spacing has been fixed on all the forms.

Apart from that, they do consistently follow Google's Material Design standard.  https://m3.material.io/components/text-fields/overview  .  When fields are blank, the label appears in the textbox.  As soon as you click to begin typing it moves to the top left corner of the field to make room for the text.
