### ISSUE TITLE
First Time Visitor Form

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#419]
We need to create a form on the website for new visitors coming to a church that uses the check-in system. If this functionality is already available, please let me know.

The scenario is as follows: a guest is considering attending the church but doesn’t want to stand in line to check in their kids. We need a way for them to fill out a form online ahead of time, so that when they arrive at the church, their information is already in the system. Upon arrival, they would simply enter their number like everyone else and print their tags.

**Comment by jzongker** [comment]
We have the ability in the B1 app for existing users to check in from their phones, but not to register a new family.  Do other chms platforms allow this?  Allowing internet visitors to create new people in you chms seems like it could be problematic.

**Comment by mbyrdLCS** [comment]
yes planning center does https://ridgechristian.churchcenter.com/people/forms/46920

**Comment by jzongker** [comment]
@Himali-Malvawala - On the profile screen where you can currently change your info, avatar, etc and it submits an approval request, let's add the option to add a family member.  It should work the same way, submitting a request to be approved which does the actual creating.

**Comment by Himali-Malvawala** [comment]
I've added the option! Once the request is approved, the person will be added to the same household.
