### ISSUE TITLE
Order of Funds in Donations

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#422]
Make the "Funds" so we can move the order. When you enter funds the last one you enter is at the top. Can we make it so we can move them up or down. The only way to move them now is to delete them and put them in reverse order. 
<img width="1259" alt="Funds Order" src="https://github.com/user-attachments/assets/b6b0b8a9-4e84-4ee6-98e6-08044bdab0c1">

**Comment by jzongker** [comment]
Would alphabetizing work instead?

**Comment by jzongker** [comment]
@KZongker - Let's sort them alphabetically and then rename "General Fund" to "(General Fund)" so it appears on top.

https://github.com/ChurchApps/B1Mobile/blob/22ac54034563396d2606eff1e014abd0218984b1/src/components/donations/FundDropDown.tsx#L10
https://github.com/ChurchApps/B1Mobile/blob/22ac54034563396d2606eff1e014abd0218984b1/src/components/donations/FundDropDown.tsx#L10

**Comment by tbyrd77** [comment]
Yes, that will work! Thanks
