### ISSUE TITLE
ACH Giving link

### ISSUE THREAD

**Issue by tbyrd77** [ChurchApps/ChurchAppsSupport#423]
Can we put instructions and a link for setting up ACH payments on the giving page? Currently, if you want to give using ACH you have to know the process to follow.

**Comment by jzongker** [comment]
We currently have these instructions when you go to link a bank account on B1.  Are those insufficient or is there another place we need to add them?

![image](https://github.com/user-attachments/assets/c2e1e252-0743-403f-affa-3e0c360dd8b3)

**Comment by tbyrd77** [comment]
That's good if the person is logged in but if they just go to the giving portal, they won't know they need to log in to give through ACH. I'm thinking of people who go to the church website, click on giving and go to the portal but have no idea they need to log in.  Maybe just a notice something like "For ACH giving log in to Chums and follow instructions" Or maybe a button that says "ACH Giving" linked to the login page.

**Comment by tbyrd77** [comment]
Here is what I put on the Tyro website. 
<img width="1158" alt="Screenshot 2024-11-26 at 7 50 55 AM" src="https://github.com/user-attachments/assets/dc191bab-237c-4c77-81d5-66887e0c5463">

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS @jzongker How about we just link [this (Logged In View) video](https://support.churchapps.org/b1/portal/donations/) on this page?

As: "Instructions for ACH Payment"
![image](https://github.com/user-attachments/assets/6a0cf0ce-02f1-435c-be0d-a879963c87a2)

**Comment by Himali-Malvawala** [comment]
@tbyrd77  I've added the link!
