### ISSUE TITLE
Recurring Donations Break When Funds Are Deleted

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/ChurchAppsSupport#429]
If you set up a recurring donation to a fund, then that fund gets deleted, no fundDonation record gets created when new transactions occur.  This causes the reports to break.

Lets have it go to their first fund alphabetically if the desired fund is missing, which should be "(General Fund)".

**Comment by jzongker** [comment]
See https://github.com/ChurchApps/GivingApi/blob/14fab484844885ad900aeb292b58c3dad2c7ac0d/src/helpers/StripeHelper.ts#L192

**Comment by Himali-Malvawala** [comment]
@jzongker I've added the code for that. Lmk if it still doesn't work.

Closing.
