### ISSUE TITLE
Videos not playing in the B1 app

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#431]
The videos will play but only after you hit pause and then play again after you open the video the video should auto play when you click on it. 

https://github.com/user-attachments/assets/0e2a329a-cb42-45e1-be45-e2a47ad0cf62

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS I Checked it on the web, and it's working fine. It's an app issue so adding a new label.
