### ISSUE TITLE
Printable's not showing up on lessons.church

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#451]
Seems to be isolated to Good news of Christmas.Ark Curriculum  Elm and Junior you can not download any of the Printable's.  They have been added but are not showing up on the site. 

 
<img width="1444" alt="Screenshot 2024-12-16 at 3 11 19 PM" src="https://github.com/user-attachments/assets/9f8eb8ab-cb73-4873-a79b-ff718ae192e5" />

![Image 12-16-24 at 3 11 PM](https://github.com/user-attachments/assets/776934d2-9b1b-4b6e-a2c3-bd666074dc61)

**Comment by Himali-Malvawala** [comment]
@mbyrdLCS Can you try adding that at the lesson level? It might be at that level in other lessons.

**Comment by mbyrdLCS** [comment]
@Himali-Malvawala It is on the Lesson level "The Good News of Christmas Week 1" is the the lesson

**Comment by Himali-Malvawala** [comment]
hmm, strange. @mbyrdLCS, Did you add the 'Slides and Printables' the same way you did in other lessons?

**Comment by mbyrdLCS** [comment]
Yes this was built the same as everything else. We do need to get this back up soon I have sevral reaching out to me and I have to manually send them files.

**Comment by jzongker** [comment]
This is fixed.  There's an automated process to zip up the "bundles" that gets stuck every now and then.  I just had to manually run /bundles/zip and then clear the cache for it to show up.
