### ISSUE TITLE
Unable to add Groups via ChuM.

### ISSUE THREAD

**Issue by redhillchurch1** [ChurchApps/ChurchAppsSupport#454]
Good day.
I am able to use the Groups + button and then add the Category name and Name, but when hitting Add button the UI monetarily flashes a couple of waiting dots and then no group is actually added the Groups section. Windows 10 via both latest MS Edge (Version 131.0.2903.112 (Official build) (64-bit)} and Chrome (Version 131.0.6778.205 (Official Build) (64-bit)) Browsers. Did notice the previous Groups add issue posted a long while back, but this is not related to that original group addition issue I don't think. Facebook page provides no answers in search and seems closed to being able to post anything to that FB group.
Any advice or if able to replicate issue would be welcome.

https://github.com/user-attachments/assets/10103208-d54d-4767-80a7-ebd7adf05c19

**Comment by Himali-Malvawala** [comment]
This is fixed now!

**Comment by redhillchurch1** [comment]
> @redhillchurch1 This is fixed now!

WOW! thank you for the quick turnaround on this. Most appreciated, especially getting tis resolved during the Xmas break and everyone's attention turned elsewhere. Thank You.
