### ISSUE TITLE
 Add a friend of a child to the member family

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/ChurchAppsSupport#87]
add a friend of a child to the member family. This is for when a child comes with a member family and not their own parents. 

This is for the chums Chekin app allowing people to add a guest for the day that will have the same check-in code

**Comment by jzongker** [comment]
When a person clicks the add friend button.  Force them to do a search of existing people first with an Create New Guest option after that search.  Make First/Last name and birthdate required fields when creating the new person record and add them with a membership status of Guest.

**Comment by jzongker** [comment]
Added with 1.25.0
